### ISSUE TITLE
Plugin Not Responding

### ISSUE THREAD

**Issue by wilguevara** [lampaa/org.apache.cordova.startapp#2]
Hello! im trying to use your plugin on my app, i follow all the installation intructions, but when i try to run this function: <code>navigator.startApp.check("com.example.hello", function(message) { /* success */
    console.log(message); // => OK
}, 
function(error) { /* error */
    console.log('47', error);
});</code>

doesn't fire any message to console.

Thanks for your time!

**Comment by lampaa** [comment]
@hmdinfo delete and reinstall plugin.
