### ISSUE TITLE
IOS cordova 3.3 

### ISSUE THREAD

**Issue by hmdinfo** [lampaa/org.apache.cordova.startapp#8]
Hello  i am trying to call the plugin always returns  47 false 

```
function show() {
    navigator.startApp.start("twitter://", function(message) { /* success */
        console.log(message); // => OK
    }, 
    function(error) { /* error */
        console.log('47', error);
    });
 }
```

i am interested in open major social apps from my app  can you please post HTML test code 
thanks 
Abdul

**Comment by lampaa** [comment]
Hi, @hmdinfo!
I update plugin, test this:
```javascript
navigator.startApp.start([["action", "VIEW"], ["twitter://user?user_id=id_num"], function(message) {
    console.log(message); // => OK
}, 
function(error) { /* error */
    console.log(error);
});
```
You can replace ```twitter://user?user_id=id_num``` to ```https://twitter.com/PROFILENAME```

**Comment by lampaa** [comment]
Hi, @hmdinfo 
Sorry, but that I do not support the development for iOS. If someone will be able to modify what he @vitorsgomes, then I'll add it to your project.
