### ISSUE TITLE
not working with IOS

### ISSUE THREAD

**Issue by piyushkhare11** [lampaa/org.apache.cordova.startapp#9]
Hi, I tried it with IOS but the plugin is not working.
While using navigator.startApp.check(), the error function gives message as false. Can you please suggest the probable issue with this.
Thanks in advance
Piyush
piyush.khare11@gmail.com

**Comment by lampaa** [comment]
Hi, @piyushkhare11 
Sorry, but that I do not support the development for iOS. If someone will be able to modify what he @vitorsgomes, then I'll add it to your project.
